<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $customers = [
            [
                'name' => 'Aung Aung',
                'email' => 'customer1@example.com',
                'phone' => '0910000001',
                'address' => 'Yangon',
                'date_of_birth' => '1995-01-15',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kyaw Kyaw',
                'email' => 'customer2@example.com',
                'phone' => '0910000002',
                'address' => 'Mandalay',
                'date_of_birth' => '1994-02-20',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hla Hla',
                'email' => 'customer3@example.com',
                'phone' => '0910000003',
                'address' => 'Bago',
                'date_of_birth' => '1996-03-12',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Su Su',
                'email' => 'customer4@example.com',
                'phone' => '0910000004',
                'address' => 'Yangon',
                'date_of_birth' => '1999-04-05',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Zaw Zaw',
                'email' => 'customer5@example.com',
                'phone' => '0910000005',
                'address' => 'Taunggyi',
                'date_of_birth' => '1993-05-22',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Min Min',
                'email' => 'customer6@example.com',
                'phone' => '0910000006',
                'address' => 'Pyay',
                'date_of_birth' => '1997-06-18',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aye Aye',
                'email' => 'customer7@example.com',
                'phone' => '0910000007',
                'address' => 'Monywa',
                'date_of_birth' => '1998-07-09',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tun Tun',
                'email' => 'customer8@example.com',
                'phone' => '0910000008',
                'address' => 'Sagaing',
                'date_of_birth' => '1992-08-14',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ei Ei',
                'email' => 'customer9@example.com',
                'phone' => '0910000009',
                'address' => 'Pathein',
                'date_of_birth' => '2000-09-30',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Win Win',
                'email' => 'customer10@example.com',
                'phone' => '0910000010',
                'address' => 'Thanlyin',
                'date_of_birth' => '1995-10-11',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Ko Ko',
                'email' => 'customer11@example.com',
                'phone' => '0910000011',
                'address' => 'Yangon',
                'date_of_birth' => '1991-11-01',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nandar',
                'email' => 'customer12@example.com',
                'phone' => '0910000012',
                'address' => 'Mandalay',
                'date_of_birth' => '1996-12-20',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Yamin',
                'email' => 'customer13@example.com',
                'phone' => '0910000013',
                'address' => 'Magway',
                'date_of_birth' => '1999-01-08',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Htun Htun',
                'email' => 'customer14@example.com',
                'phone' => '0910000014',
                'address' => 'Meiktila',
                'date_of_birth' => '1994-02-27',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'May Myat',
                'email' => 'customer15@example.com',
                'phone' => '0910000015',
                'address' => 'Lashio',
                'date_of_birth' => '2001-03-16',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Zin Min',
                'email' => 'customer16@example.com',
                'phone' => '0910000016',
                'address' => 'Myitkyina',
                'date_of_birth' => '1993-04-04',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thazin',
                'email' => 'customer17@example.com',
                'phone' => '0910000017',
                'address' => 'Dawei',
                'date_of_birth' => '1998-05-25',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Phyo Min',
                'email' => 'customer18@example.com',
                'phone' => '0910000018',
                'address' => 'Sittwe',
                'date_of_birth' => '1992-06-13',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hnin Ei',
                'email' => 'customer19@example.com',
                'phone' => '0910000019',
                'address' => 'Pyin Oo Lwin',
                'date_of_birth' => '1997-07-07',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soe Min',
                'email' => 'customer20@example.com',
                'phone' => '0910000020',
                'address' => 'Kalay',
                'date_of_birth' => '1990-08-30',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Myat Noe',
                'email' => 'customer21@example.com',
                'phone' => '0910000021',
                'address' => 'Pakokku',
                'date_of_birth' => '1995-09-19',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nyein Chan',
                'email' => 'customer22@example.com',
                'phone' => '0910000022',
                'address' => 'Mawlamyine',
                'date_of_birth' => '1994-10-10',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thin Thin',
                'email' => 'customer23@example.com',
                'phone' => '0910000023',
                'address' => 'Hpa-An',
                'date_of_birth' => '1999-11-28',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Aung Min',
                'email' => 'customer24@example.com',
                'phone' => '0910000024',
                'address' => 'Shwebo',
                'date_of_birth' => '1991-12-06',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Khin Lay',
                'email' => 'customer25@example.com',
                'phone' => '0910000025',
                'address' => 'Yenangyaung',
                'date_of_birth' => '1996-01-23',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'name' => 'Lin Htet',
                'email' => 'customer26@example.com',
                'phone' => '0910000026',
                'address' => 'Taungoo',
                'date_of_birth' => '1998-02-14',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Cherry Myint',
                'email' => 'customer27@example.com',
                'phone' => '0910000027',
                'address' => 'Aunglan',
                'date_of_birth' => '2000-03-09',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paing Oo',
                'email' => 'customer28@example.com',
                'phone' => '0910000028',
                'address' => 'Myeik',
                'date_of_birth' => '1993-04-18',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'San San',
                'email' => 'customer29@example.com',
                'phone' => '0910000029',
                'address' => 'Bhamo',
                'date_of_birth' => '1997-05-27',
                'gender' => 'female',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hein Min',
                'email' => 'customer30@example.com',
                'phone' => '0910000030',
                'address' => 'Kyaing Tong',
                'date_of_birth' => '1992-06-15',
                'gender' => 'male',
                'user_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
         Customer::insert($customers);
    }
}
